"""Data contracts that flow between agents.

These schemas are the seams of the system. They're deliberately conservative —
field names that map onto how the founder talks about his customers, not internal
agent jargon. Expect them to evolve after the founder call (especially Tier
definitions and the Crop list), but the *shape* should be stable.

Conventions:
- All timestamps are timezone-aware UTC.
- All free-text fields generated by an LLM must be paired with at least one
  Evidence object. No claim without a citation.
- IDs are deterministic where possible (e.g., USDA INTEGRITY operation_id) so
  records can be deduped across sources.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field, HttpUrl


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class Tier(str, Enum):
    """Buyer tier, derived from the founder's existing customer set.

    Concrete definitions are pinned after the founder call and live in
    `docs/brief.md`. Treat these as placeholders that map onto common B2B
    segmentation: T1 = best-fit / highest LTV, T3 = plausible but lower priority.
    """

    T1 = "tier_1"
    T2 = "tier_2"
    T3 = "tier_3"
    UNFIT = "unfit"


class Crop(str, Enum):
    """Crops that drive Redland buying patterns. Extend after the founder call.

    Listed by the founder's revealed preference, not USDA taxonomy.
    """

    AVOCADO = "avocado"
    MANGO = "mango"
    LYCHEE = "lychee"
    LONGAN = "longan"
    PASSION_FRUIT = "passion_fruit"
    DRAGON_FRUIT = "dragon_fruit"
    PAPAYA = "papaya"
    BANANA = "banana"
    CITRUS = "citrus"
    WINTER_VEG = "winter_vegetables"  # tomato, squash, beans, sweet corn
    NURSERY_ORNAMENTAL = "nursery_ornamental"
    OTHER = "other"


class SignalKind(str, Enum):
    """Triage agent output. Each signal is a *reason to reach out now*."""

    NEW_CERTIFICATION = "new_certification"          # USDA Organic INTEGRITY
    LOST_CERTIFICATION = "lost_certification"
    BMP_ENROLLMENT = "bmp_enrollment"                # FDACS Best Management Practices
    HURRICANE_DAMAGE = "hurricane_damage"            # NOAA
    FREEZE_EVENT = "freeze_event"                    # NOAA / NWS Miami
    FIELD_DAY = "field_day"                          # UF/IFAS TREC
    PRESS_MENTION = "press_mention"                  # ag trade press EN/ES
    NEW_LICENSE = "new_license"                      # FDACS nursery licenses
    OTHER = "other"


# ---------------------------------------------------------------------------
# Evidence
# ---------------------------------------------------------------------------


class Evidence(BaseModel):
    """A single citation supporting a claim made by an agent.

    Every LLM-generated assertion in this system must be paired with at least
    one Evidence object. This is what makes outreach defensible to the founder
    and what makes recall measurable.
    """

    source: Literal[
        "INTEGRITY", "NASS", "FDACS", "NOAA", "TREC", "PRESS", "CUSTOMER_DB", "WEB"
    ] = Field(..., description="Which data source this evidence came from.")
    url: HttpUrl | None = Field(None, description="Canonical URL, if any.")
    snapshot_path: str | None = Field(
        None,
        description="Path to a local snapshot (bulk download row, screenshot, etc.).",
    )
    quote: str | None = Field(
        None,
        description="Verbatim quote or extracted value supporting the claim.",
    )
    retrieved_at: datetime = Field(..., description="When this evidence was fetched.")


# ---------------------------------------------------------------------------
# Lead (Discovery agent output)
# ---------------------------------------------------------------------------


class Lead(BaseModel):
    """A grower operation discovered in the Redland universe.

    Produced by the Discovery agent. Represents the *operation*, not a contact.
    Contacts are attached separately so we can update them without re-running
    discovery.
    """

    # Identity
    lead_id: str = Field(..., description="Stable internal ID (slug of name + zip).")
    operation_name: str
    dba_names: list[str] = Field(default_factory=list)

    # Location
    address: str | None = None
    city: str | None = None
    zip_code: str | None = None
    latitude: float | None = None
    longitude: float | None = None

    # Operation profile
    is_organic_certified: bool = False
    integrity_operation_id: str | None = Field(
        None, description="USDA Organic INTEGRITY operation_id, if applicable."
    )
    fdacs_license_number: str | None = None
    primary_crops: list[Crop] = Field(default_factory=list)
    estimated_acres: float | None = None

    # Contacts (sparse — most leads start with operation only)
    primary_contact_name: str | None = None
    primary_contact_email: str | None = None
    primary_contact_phone: str | None = None
    primary_contact_language: Literal["en", "es", "unknown"] = "unknown"

    # Provenance
    discovered_at: datetime
    sources: list[Evidence] = Field(
        default_factory=list,
        description="One Evidence object per data source that contributed to this Lead.",
    )

    # Cross-reference status
    is_existing_customer: bool = Field(
        False,
        description="Set by the orchestrator after cross-referencing the founder's customer list. "
        "True leads are filtered out of qualification.",
    )
    is_previously_contacted: bool = False


# ---------------------------------------------------------------------------
# Qualification (Qualification agent output)
# ---------------------------------------------------------------------------


class Qualification(BaseModel):
    """Tier + score + rationale for a single Lead."""

    lead_id: str
    tier: Tier
    score: int = Field(..., ge=0, le=100, description="Composite ICP-fit score.")
    rationale: str = Field(
        ...,
        description=(
            "2-4 sentence rationale, in the founder's voice. Must reference at "
            "least one piece of evidence by source."
        ),
    )
    evidence: list[Evidence] = Field(
        ..., min_length=1, description="At least one citation is required."
    )

    # Sub-scores let us debug which dimension drove the verdict.
    crop_fit: int = Field(..., ge=0, le=100)
    scale_fit: int = Field(..., ge=0, le=100)
    organic_alignment: int = Field(..., ge=0, le=100)
    geographic_proximity: int = Field(..., ge=0, le=100)

    qualified_at: datetime
    prompt_version: str = Field(
        ..., description="System prompt version (e.g., 'qualification@v2'). Logged for evals."
    )


# ---------------------------------------------------------------------------
# Signal (Triage agent output)
# ---------------------------------------------------------------------------


class Signal(BaseModel):
    """A reason-to-reach-out-now event surfaced by the Triage agent.

    Signals are attached to Leads by the orchestrator. The Outreach agent uses
    the most recent relevant Signal as the hook for first-touch messaging.
    """

    signal_id: str
    lead_id: str | None = Field(
        None,
        description="May be unattached at first; orchestrator resolves to a Lead.",
    )
    kind: SignalKind
    headline: str = Field(..., description="One-line human-readable summary.")
    detail: str | None = None
    occurred_at: datetime
    detected_at: datetime
    evidence: list[Evidence] = Field(..., min_length=1)
    is_stale: bool = Field(
        False,
        description="Signals older than ~30 days for weather, ~90 days for certifications "
        "are considered stale and shouldn't drive outreach.",
    )


# ---------------------------------------------------------------------------
# Outreach (Outreach agent output)
# ---------------------------------------------------------------------------


class OutreachTouch(BaseModel):
    """A single message in a 3-touch outreach sequence."""

    sequence_index: int = Field(..., ge=1, le=3)
    channel: Literal["email", "sms", "phone_script"] = "email"
    language: Literal["en", "es"]
    subject: str | None = None  # phone_script has no subject
    body: str
    send_after_days: int = Field(
        ..., ge=0, description="Days to wait after the previous touch (0 for the first)."
    )


class OutreachDraft(BaseModel):
    """A full outreach package for one Lead, ready for founder approval.

    The founder sees this in the Streamlit UI and can approve / edit / reject.
    Nothing is sent automatically.
    """

    lead_id: str
    qualification_score: int
    primary_signal_id: str | None = Field(
        None,
        description="The Signal that motivates first-touch, if any.",
    )

    # The hook — *why this lead, why now*. Surfaced prominently in the UI.
    why_this_message: str = Field(
        ...,
        description="1-2 sentence justification for sending now. Must cite a Signal or "
        "a customer-list cross-reference (e.g., 'neighbors a Tier-1 customer').",
    )

    # Talking points for the founder if the lead replies.
    talk_track: list[str] = Field(
        default_factory=list,
        description="3-5 bullet points the founder can use on a follow-up call.",
    )

    touches: list[OutreachTouch] = Field(..., min_length=1, max_length=3)
    drafted_at: datetime
    prompt_version: str
